In [5]:
import pandas as pd
import numpy as mp
import seaborn as sns
import matplotlib.pyplot as plt
import folium
import json
import matplotlib as mpl
plt.rc('font', family='Malgun Gothic')
import os
print(os.getcwd())

C:\Suwon_Security

In [91]:
# 전국 & 서울 + 각 구별 인구 & 수원 & 창원 & 진주 인구 데이터 ( 2019년 )
df_pop = pd.read_csv("data/행정구역_시군구_별_주민등록세대수.csv", encoding = 'ansi')
df_pop.columns = ['city','pop']
df_pop.set_index('city', inplace=True)
pop_seoul = df_pop.iloc[0:27]
pop_else = df_pop.loc[['수원시', '창원시', '진주시']]
df_pop = pop_seoul.append(pop_else)
display(df_pop)

df_pop.to_csv('output/2019년_전국+서울전체+서울구별+수원+창원+진주_인구.csv', encoding='utf-8')

            pop
city
전국     23383689
서울특별시   4421143
종로구       73652
중구        63267
용산구      111177
성동구      134620
광진구      167438
동대문구     167591
중랑구      185497
성북구      195099
강북구      144573
도봉구      138582
노원구      217269
은평구      214181
서대문구     143712
마포구      179541
양천구      181281
강서구      270389
구로구      180424
금천구      116545
영등포구     186360
동작구      184825
관악구      276182
서초구      171497
강남구      234218
송파구      282018
강동구      201205
수원시      516103
창원시      450188
진주시      156800

In [94]:
# 서울 관할구 연령별 디테일 인구특성 분포 (2021 2분기)

df_seoul = pd.read_csv("data/연령별_구별_서울시_주민등록인구_2분기_2021.csv", encoding = 'ansi')
df_seoul.drop(['연도','분기'],axis=1,inplace=True)
#print(df_seoul.dtypes)
df_seoul.replace(' ', 0, inplace=True)
df_seoul['연령90_94세'] = df_seoul['연령90_94세'].astype(int)
df_seoul['연령95_100세'] = pd.to_numeric(df_seoul['연령95_100세'])
df_seoul['연령_100세이상'] =pd.to_numeric(df_seoul['연령_100세이상'])
#display(df_seoul.info())
#print(df_seoul.isblank().sum(axis=1))
df_seoul['10세 미만'] = df_seoul['연령0_4세']+df_seoul['연령5_9세']
df_seoul['10대'] = df_seoul['연령10_14세']+df_seoul['연령15_19세']
df_seoul['20대'] = df_seoul['연령20_24세']+df_seoul['연령25_29세']
df_seoul['30대'] = df_seoul['연령30_34세']+df_seoul['연령35_39세']
df_seoul['40대'] = df_seoul['연령40_44세']+df_seoul['연령45_49세']
df_seoul['50대'] = df_seoul['연령50_54세']+df_seoul['연령55_59세']
df_seoul['60대'] = df_seoul['연령60_64세']+df_seoul['연령65_69세']
df_seoul['70세 이상'] = df_seoul['연령70_74세']+df_seoul['연령75_79세']+df_seoul['연령80_84세']+df_seoul['연령85_89세']+df_seoul['연령90_94세']+df_seoul['연령95_100세']+df_seoul['연령_100세이상']

df_seoul.drop(df_seoul.columns[3:24],axis=1,inplace=True)
df_seoul.drop(df_seoul.index[38],axis=0,inplace=True)
display(df_seoul)

df_seoul.to_csv('output/2021년_서울_관할지역_연령별_내외국인분포.csv', encoding='utf-8')

,행정구역,구분,합계,10세 미만,10대,20대,30대,40대,50대,60대,70세 이상
0,종로구,한국인,146029,7275,10684,23147,19595,21433,24939,20192,18764
1,종로구,등록외국,9077,239,345,4551,1410,1027,1004,403,98
2,중구,한국인,123016,6505,6663,18323,19881,17738,20203,17756,15947
3,중구,등록외국,9243,489,435,3071,1877,1277,1356,571,167
4,용산구,한국인,226378,13157,15144,33605,38161,34772,36432,28855,26252
5,용산구,등록외국,14287,1281,1055,2225,3724,2949,2030,767,256
6,성동구,한국인,289162,19842,19413,44374,47706,43988,46514,37132,30193
7,성동구,등록외국,6605,230,184,2800,1221,781,961,355,73
8,광진구,한국인,342481,18576,25320,62352,55128,51276,53830,43531,32468
9,광진구,등록외국,12825,639,464,5036,2183,1321,2301,779,102
10,동대문구,한국인인,338040,19982,23245,56158,49262,49475,52297,46971,40650
11,동대문구,등록외국,14219,320,422,8884,2051,937,1121,395,89
12,중랑구,한국인,389972,22029,25952,55480,57050,56493,68222,59813,44933
13,중랑구,등록외국,4707,325,184,1109,1252,674,841,274,48
14,성북구,한국인,433658,28368,36669,66183,59249,68737,69033,56027,49392
15,성북구,등록외국,9548,279,413,5385,1669,802,667,253,80
16,강북구,한국인,302645,14906,21310,41995,37702,45257,51740,46816,42919
17,강북구,등록외국,3448,153,80,1081,804,499,542,230,59
18,도봉구,한국인,320365,17841,24819,42520,39828,47191,56062,50807,41297
19,도봉구,등록외국,2054,87,63,569,558,344,310,107,16
20,노원구,한국인,515997,31763,51468,71705,63730,83729,87067,69672,56863
21,노원구,등록외국,4008,118,183,1862,829,437,394,150,35
22,은평구,한국인,475371,28620,37782,66395,67380,75071,76763,65915,57445
23,은평구,등록외국,4038,189,194,747,1055,691,752,310,100
24,서대문구,한국인,307070,19452,23065,49525,44493,46171,48627,39141,36596
25,서대문구,등록외국,10629,243,524,5488,1748,987,843,541,255
26,마포구,한국인,370132,24276,28115,61815,63856,60539,54490,40492,36549
27,마포구,등록외국,9852,333,348,4233,2184,1159,948,472,175
28,양천구,한국인,450992,30688,50002,58724,56731,77790,76068,59438,41551
29,양천구,등록외국,3296,135,115,465,789,622,830,269,71
30,강서구,한국인,577519,38228,44017,86728,98479,90187,84710,78490,56680
31,강서구,등록외국,5476,312,126,796,1541,965,1177,449,110
32,구로구,한국인,399266,26799,29575,54803,61653,62047,62305,56937,45147
33,구로구,등록외국,25316,1699,785,1821,4849,4404,8474,2916,368
34,금천구,한국인,230168,12028,14295,37184,35651,32099,39505,33986,25420
35,금천구,등록외국,14517,1062,467,933,2651,2610,5062,1540,192
36,영등포구,한국인,377421,25422,23873,59111,69267,55865,56182,47717,39984
37,영등포구,등록외국,24954,1645,865,1661,4498,4312,8586,2941,446
39,동작구,한국인,387847,23873,27291,65435,61569,58061,57788,50031,43799
40,동작구,등록외국,9384,311,272,3484,1554,1004,1878,762,119
41,관악구,한국인,488800,21044,27873,108741,85734,66796,67131,59620,51861
42,관악구,등록외국,13898,641,462,3195,2928,1863,3367,1256,186
43,서초구,한국인,418407,32547,44845,53637,61166,76005,62969,48173,39065
44,서초구,등록외국,3767,262,249,619,1040,829,539,180,49
45,강남구,한국인,531375,35384,58183,71666,79063,97714,80287,60385,48693
46,강남구,등록외국,4732,114,152,1319,1570,788,516,204,69
47,송파구,한국인,658670,48533,57871,92215,107398,107534,101179,86178,57762
48,송파구,등록외국,5671,271,151,854,1546,998,1354,408,89
49,강동구,한국인,465209,35388,39098,61387,72596,75103,71889,65729,44019
50,강동구,등록외국,3885,196,118,634,971,684,927,304,51

In [86]:
# 행정구역 별 통계치
grouped_area = df_seoul.groupby(['행정구역'])
#print(grouped_area)
for key, group in grouped_area :
    print('- area : ', key)
    print(group)
    print('\n')

- area :  강남구
   행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
45  강남구   한국인  531375   35384  58183  71666  79063  97714  80287  60385
46  강남구  등록외국    4732     114    152   1319   1570    788    516    204

    70세 이상
45   48693
46      69


- area :  강동구
   행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
49  강동구   한국인  465209   35388  39098  61387  72596  75103  71889  65729
50  강동구  등록외국    3885     196    118    634    971    684    927    304

    70세 이상
49   44019
50      51


- area :  강북구
   행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
16  강북구   한국인  302645   14906  21310  41995  37702  45257  51740  46816
17  강북구  등록외국    3448     153     80   1081    804    499    542    230

    70세 이상
16   42919
17      59


- area :  강서구
   행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
30  강서구   한국인  577519   38228  44017  86728  98479  90187  84710  78490
31  강서구  등록외국    5476     312    126    796   1541    965   1177    449

    70세 이상
30   56680
31     110


- area :  관악구
   행정구역    구분      합계  10세 미만    10대     20대    30대    40대    50대    60대  \
41  관악구   한국인  488800   21044  27873  108741  85734  66796  67131  59620
42  관악구  등록외국   13898     641    462    3195   2928   1863   3367   1256

    70세 이상
41   51861
42     186


- area :  광진구
  행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  70세 이상
8  광진구   한국인  342481   18576  25320  62352  55128  51276  53830  43531   32468
9  광진구  등록외국   12825     639    464   5036   2183   1321   2301    779     102


- area :  구로구
   행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
32  구로구   한국인  399266   26799  29575  54803  61653  62047  62305  56937
33  구로구  등록외국   25316    1699    785   1821   4849   4404   8474   2916

    70세 이상
32   45147
33     368


- area :  금천구
   행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
34  금천구   한국인  230168   12028  14295  37184  35651  32099  39505  33986
35  금천구  등록외국   14517    1062    467    933   2651   2610   5062   1540

    70세 이상
34   25420
35     192


- area :  노원구
   행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
20  노원구   한국인  515997   31763  51468  71705  63730  83729  87067  69672
21  노원구  등록외국    4008     118    183   1862    829    437    394    150

    70세 이상
20   56863
21      35


- area :  도봉구
   행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
18  도봉구   한국인  320365   17841  24819  42520  39828  47191  56062  50807
19  도봉구  등록외국    2054      87     63    569    558    344    310    107

    70세 이상
18   41297
19      16


- area :  동대문구
    행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
10  동대문구  한국인인  338040   19982  23245  56158  49262  49475  52297  46971
11  동대문구  등록외국   14219     320    422   8884   2051    937   1121    395

    70세 이상
10   40650
11      89


- area :  동작구
   행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
39  동작구   한국인  387847   23873  27291  65435  61569  58061  57788  50031
40  동작구  등록외국    9384     311    272   3484   1554   1004   1878    762

    70세 이상
39   43799
40     119


- area :  마포구
   행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
26  마포구   한국인  370132   24276  28115  61815  63856  60539  54490  40492
27  마포구  등록외국    9852     333    348   4233   2184   1159    948    472

    70세 이상
26   36549
27     175


- area :  서대문구
    행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
24  서대문구   한국인  307070   19452  23065  49525  44493  46171  48627  39141
25  서대문구  등록외국   10629     243    524   5488   1748    987    843    541

    70세 이상
24   36596
25     255


- area :  서초구
   행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
43  서초구   한국인  418407   32547  44845  53637  61166  76005  62969  48173
44  서초구  등록외국    3767     262    249    619   1040    829    539    180

    70세 이상
43   39065
44      49


- area :  성동구
  행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  70세 이상
6  성동구   한국인  289162   19842  19413  44374  47706  43988  46514  37132   30193
7  성동구  등록외국    6605     230    184   2800   1221    781    961    355      73


- area :  성북구
   행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
14  성북구   한국인  433658   28368  36669  66183  59249  68737  69033  56027
15  성북구  등록외국    9548     279    413   5385   1669    802    667    253

    70세 이상
14   49392
15      80


- area :  송파구
   행정구역    구분      합계  10세 미만    10대    20대     30대     40대     50대    60대  \
47  송파구   한국인  658670   48533  57871  92215  107398  107534  101179  86178
48  송파구  등록외국    5671     271    151    854    1546     998    1354    408

    70세 이상
47   57762
48      89


- area :  양천구
   행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
28  양천구   한국인  450992   30688  50002  58724  56731  77790  76068  59438
29  양천구  등록외국    3296     135    115    465    789    622    830    269

    70세 이상
28   41551
29      71


- area :  영등포구
    행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
36  영등포구   한국인  377421   25422  23873  59111  69267  55865  56182  47717
37  영등포구  등록외국   24954    1645    865   1661   4498   4312   8586   2941

    70세 이상
36   39984
37     446


- area :  용산구
  행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  70세 이상
4  용산구   한국인  226378   13157  15144  33605  38161  34772  36432  28855   26252
5  용산구  등록외국   14287    1281   1055   2225   3724   2949   2030    767     256


- area :  은평구
   행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
22  은평구   한국인  475371   28620  37782  66395  67380  75071  76763  65915
23  은평구  등록외국    4038     189    194    747   1055    691    752    310

    70세 이상
22   57445
23     100


- area :  종로구
  행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  70세 이상
0  종로구   한국인  146029    7275  10684  23147  19595  21433  24939  20192   18764
1  종로구  등록외국    9077     239    345   4551   1410   1027   1004    403      98


- area :  중구
  행정구역    구분      합계  10세 미만   10대    20대    30대    40대    50대    60대  70세 이상
2   중구   한국인  123016    6505  6663  18323  19881  17738  20203  17756   15947
3   중구  등록외국    9243     489   435   3071   1877   1277   1356    571     167


- area :  중랑구
   행정구역    구분      합계  10세 미만    10대    20대    30대    40대    50대    60대  \
12  중랑구   한국인  389972   22029  25952  55480  57050  56493  68222  59813
13  중랑구  등록외국    4707     325    184   1109   1252    674    841    274

    70세 이상
12   44933
13      48